[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Testing"
authors = [{name = "Avril Coghlan", email = "alc@sanger.ac.uk"}]
dynamic = ["version", "description"]

